apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/maaanish/k8s-argocd.git'
    targetRevision: master
    path: overlays/dev1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
   automated:
     selfHeal: true
     prune: true