apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-jenkins-v2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: app-off-apps/dev1/jenkins
    repoURL: "https://github.com/maaanish/k8s-argocd-apps.git"
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  project: default